name: Update Docker Compose on Droplet

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - '.github/workflows/docker-compose-restart.yml'
      - 'docker-compose.prod.yaml'

jobs:
  copy-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Copy docker-compose.prod.yaml to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP_ADDRESS }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "docker-compose.prod.yaml"
          target: "/root"

  restart-application:
    needs: copy-docker-compose
    uses: ASE-WS23-GruppeA/workout-tracker/.github/workflows/docker-compose-restart.yml@main
