name: Restart Services with Docker Compose

on:
  workflow_call:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Services
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_IP_ADDRESS }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            docker compose -f docker-compose.prod.yaml down --remove-orphans
            docker compose -f docker-compose.prod.yaml up --pull always --detach