name: Restart Services with Docker Compose

on:
  workflow_call:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP_ADDRESS }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            docker compose down --remove-orphans
            docker compose up --pull always --detach