name: Build and Test with Gradle

on:
  workflow_call:
    inputs:
      java_version:
        required: false
        type: string
        default: '21'
      gradle_version:
        required: false
        type: string
        default: '8.5'
      build_artifact_name:
        required: false
        type: string
        default: 'build_artifact'
      build_artifact_path:
        required: false
        type: string
        default: 'build'

jobs:
  build-and-test-with-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ inputs.gradle_version }}

      - name: Execute Gradle build
        run: ./gradlew clean build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.build_artifact_name }}
          path: ${{ inputs.build_artifact_path }}
