name: Test with Node

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '16'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test